<a href="https://colab.research.google.com/github/apoorvakarnwal/google-colab/blob/main/nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **BAG OF WORDS MODEL**

In [1]:
class Category:
  BOOKS="BOOKS"
  CLOTHING="CLOTHING"

train_x= ["I love the book", "This is a great book", "The fit is great", "I love the shoes"]
train_y= [Category.BOOKS, Category.BOOKS, Category.CLOTHING, Category.CLOTHING]

In [2]:
#unigram (tokenise 1 word)
from sklearn.feature_extraction.text import CountVectorizer
vectorizer= CountVectorizer(binary=True)
X=vectorizer.fit_transform(train_x)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['book' 'fit' 'great' 'is' 'love' 'shoes' 'the' 'this']
[[1 0 0 0 1 0 1 0]
 [1 0 1 1 0 0 0 1]
 [0 1 1 1 0 0 1 0]
 [0 0 0 0 1 1 1 0]]


In [3]:
from sklearn import svm
clf_svm= svm.SVC(kernel='linear')
clf_svm.fit(X, train_y)

test_x= vectorizer.transform(["I like reading the book"])
clf_svm.predict(test_x)

array(['BOOKS'], dtype='<U8')

In [4]:
#bigram (tokenise 2 word)
from sklearn.feature_extraction.text import CountVectorizer
vectorizer= CountVectorizer(binary=True, ngram_range=(2,2))
X=vectorizer.fit_transform(train_x)
print(vectorizer.get_feature_names_out())
print(X.toarray())

from sklearn import svm
clf_svm= svm.SVC(kernel='linear')
clf_svm.fit(X, train_y)

test_x= vectorizer.transform(["I like reading the book"])
clf_svm.predict(test_x)

['fit is' 'great book' 'is great' 'love the' 'the book' 'the fit'
 'the shoes' 'this is']
[[0 0 0 1 1 0 0 0]
 [0 1 1 0 0 0 0 1]
 [1 0 1 0 0 1 0 0]
 [0 0 0 1 0 0 1 0]]


array(['BOOKS'], dtype='<U8')

# **WORD VECTORS**

In [31]:
!pip install spacy
!python -m spacy download en_core_web_md

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 53.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [6]:
import spacy

nlp=spacy.load("en_core_web_md")

In [7]:
print(train_x)

['I love the book', 'This is a great book', 'The fit is great', 'I love the shoes']


In [14]:
docs = [nlp(text) for text in train_x]

In [17]:
train_x_word_vec= [doc.vector for doc in docs]

In [18]:
clf_svm_word_vec= svm.SVC(kernel='linear')
clf_svm_word_vec.fit(train_x_word_vec, train_y)

SVC(kernel='linear')

In [20]:
doc_word_vec=nlp("I love the book")
test_x_word_vec= doc_word_vec.vector.reshape(1, -1)
clf_svm_word_vec.predict(test_x_word_vec)

ValueError: Expected 2D array, got 1D array instead:
array=[-7.33089983e-01 -5.24749886e-03 -2.35488251e-01  1.59274936e-02
  9.66347754e-02  1.56278491e-01  1.38615012e-01 -1.82292491e-01
  8.84527490e-02  1.54077005e+00 -2.41762251e-01 -8.96672532e-02
  1.74057245e-01  3.10127772e-02  4.62116897e-02 -5.05267493e-02
 -1.48660004e-01  1.03792381e+00 -1.71565011e-01 -6.28000051e-02
  1.03982493e-01  1.28997505e-01  1.35554761e-01 -2.06535250e-01
 -2.21828252e-01 -1.54980987e-01 -2.25717485e-01 -2.63060927e-01
  2.91349851e-02  9.59425047e-02 -2.11517513e-02  3.45300019e-01
 -1.88805014e-01  1.19102523e-02  1.82815492e-01  1.35538995e-01
 -1.14783749e-01  2.49261260e-01 -1.00740008e-01  6.52624816e-02
 -1.29889250e-01  1.79949999e-02 -1.20909005e-01 -2.06174999e-02
  1.49652511e-01  1.26080498e-01  4.98107485e-02  1.36212513e-01
 -6.19465038e-02  1.98888257e-01 -1.23281501e-01  9.30762440e-02
 -8.31630006e-02 -1.11451503e-02  3.28723229e-02 -1.49444744e-01
 -3.78984734e-02 -1.56752497e-01 -1.67660996e-01 -1.64857253e-01
 -1.43127844e-01 -1.18127748e-01 -1.83716238e-01  1.67531759e-01
  2.22494990e-01 -2.22010002e-01 -9.77685004e-02 -1.69120744e-01
  5.66497445e-02 -1.52496211e-02  3.93482484e-02 -3.64200026e-02
  3.26526999e-01 -1.68735996e-01 -1.08596012e-01  7.39234984e-02
  1.01182498e-01  6.10624962e-02  3.49889919e-02  3.65122497e-01
 -1.50467515e-01  1.74932554e-02  2.23723099e-01 -2.22526252e-01
  3.95052508e-02  5.91410026e-02  3.80437493e-01 -3.53190005e-01
  1.39151245e-01 -1.05114751e-01  3.03142481e-02 -2.49097750e-01
 -6.95675015e-02  5.91125041e-02 -3.53082493e-02 -1.52070746e-01
  1.83142245e-01  2.06560358e-01  4.03746963e-04 -1.82502240e-01
  6.72705024e-02 -2.28220493e-01 -8.42407495e-02 -2.87250057e-03
  3.33609998e-01 -8.08547497e-01  4.50547524e-02  1.67957246e-01
 -8.33954960e-02  3.78089994e-02  2.35780012e-02 -1.00685000e-01
  1.22911498e-01 -3.81637245e-01 -3.22119258e-02 -3.80277559e-02
 -5.44138737e-02 -2.07415000e-01 -1.76978990e-01 -1.18791744e-01
  1.89626485e-01 -5.00249863e-03 -4.93000038e-02 -2.28235006e-01
  3.79942507e-02  2.92323500e-01 -6.90475032e-02 -1.34443998e-01
 -3.86012420e-02 -1.89242989e-01 -1.24293245e-01 -2.42224753e-01
  5.49830049e-02  8.88489187e-02  1.60198510e-01  3.67865004e-02
 -2.23826006e-01  6.23224974e-02 -1.43966258e-01 -2.89364979e-02
 -2.08123016e+00 -1.45465747e-01 -1.22755006e-01  5.03720045e-02
 -1.71651497e-01 -9.70075056e-02  8.24250057e-02  1.13308743e-01
 -2.98660487e-01 -1.93424985e-01  1.50652498e-01  9.66809988e-02
  2.26632491e-01  5.59002534e-02  6.71927482e-02  9.84297469e-02
 -1.33077502e-01  5.22324815e-02 -1.09632745e-01 -1.65625066e-02
  4.13108990e-02  1.30874008e-01 -2.50815004e-02  1.29675046e-02
 -1.68946251e-01  5.57840019e-02  5.59324995e-02  6.79262504e-02
 -1.18319973e-01 -2.26592511e-01 -2.84274928e-02 -1.66105002e-01
  9.65466499e-02 -4.10465002e-01  2.17164993e-01  2.11599991e-02
 -2.82057494e-01  1.05725043e-02  1.22214004e-01 -1.40052497e-01
  1.05170757e-01 -4.94959988e-02 -4.71213520e-01 -1.46102250e-01
  9.39234942e-02  1.72262505e-01 -1.03281498e-01 -2.11037755e-01
  3.06160003e-01  1.06317796e-01  2.26737529e-01 -3.51342469e-01
 -3.53824943e-02 -2.30883658e-02  1.76150009e-01  7.88392425e-02
  9.73749980e-02 -2.10095003e-01 -2.03574896e-02 -3.90209965e-02
  1.28568500e-01 -1.22218698e-01  1.47977501e-01 -1.43759251e-01
  1.33850127e-02 -2.66407490e-01 -7.89899975e-02 -1.33210242e-01
  7.85610005e-02  1.90067478e-02 -8.75902474e-02  5.07799983e-02
  2.71465033e-02  1.96300000e-02  1.36395648e-01 -1.73116744e-01
 -1.41265005e-01  7.22225010e-02 -2.92017490e-01  1.07676499e-01
  2.39373557e-02 -6.60865009e-02 -2.01092511e-01 -3.79764974e-01
  2.43160017e-02 -9.12735015e-02 -2.44716495e-01 -6.59702569e-02
 -1.09315991e-01  6.98744953e-02 -2.81182498e-01 -1.77875489e-01
  1.90767005e-01 -4.53622453e-02 -1.09547995e-01 -1.04660496e-01
  3.41754735e-01 -2.97694989e-02  1.08115740e-01 -4.52124998e-02
  5.70219979e-02 -8.27712417e-02 -1.06687509e-02  4.78593782e-02
  1.02178499e-01 -7.90325031e-02 -2.50474978e-02  9.35897529e-02
 -9.09850001e-02  1.97501510e-01  9.36162472e-02 -2.22609490e-01
  1.63676754e-01  1.70581751e-02  3.27795446e-02  1.28970236e-01
 -9.64049920e-02 -7.32752457e-02 -1.66480988e-01 -1.76408753e-01
 -1.48026496e-01 -1.71367526e-02  4.44895029e-02  2.29227498e-01
  2.68110007e-01 -8.87151062e-02 -2.04077456e-02  1.33444250e-01
  5.75505018e-01  1.76446751e-01  3.17427516e-02 -4.27357495e-01
 -1.90099254e-01 -1.20554991e-01  5.05542383e-03 -2.46447504e-01
 -3.10188740e-01 -2.44999994e-02 -5.48632517e-02  1.12394750e-01
  4.25367430e-02 -1.47271991e-01 -6.36419952e-02  5.84555082e-02
 -8.52750018e-02  1.61836058e-01  2.16748938e-01 -2.49117509e-01
 -1.43582255e-01 -1.71492502e-01 -9.85517502e-02 -2.14638233e-01
 -1.32202491e-01 -2.51144975e-01 -5.27722538e-02  1.50995508e-01
  3.53277624e-02 -1.23240001e-01  1.14262253e-01  1.09529994e-01].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.